[package]
name = "minesweeper"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.13.1", features = ["image", "tokio"] }
log = "0.4.27"
rand = "0.9.1"
simple_logger = "5.0.0"
